Feature/post creation page
MatheusHenriqueSS/maratonic pull request #12
Opened 2023-05-01 02:48 UTC by Danihosomi

Closes: #5 
## Change Log:
- Cria editor de markdown
- Salve texto no banco de Dados
-  Lista todos os posts criados

2023-05-01 16:37 UTC, gabsrp2002 requested changes
Coloquei alguns comentários. Além disso, o app não está rodando corretamente.

Ele abre assim quando é testado no safari:

<img width="1274" alt="Screenshot 2023-05-01 at 12 03 33" src="https://user-images.githubusercontent.com/72114357/235489157-1126495e-bc25-4f16-a4aa-440a1ee9138a.png">

2023-05-01 16:37 UTC, gabsrp2002 commented on front/src/components/MarkDown/MarkDown.tsx
> +import { useContext, useState } from 'react'
_useContext_ não é usada.

2023-05-01 16:37 UTC, gabsrp2002 commented on front/src/pages/index.tsx
> +const inter = Inter({ subsets: ['latin'] })
_inter_ não é usado.

2023-05-01 16:37 UTC, gabsrp2002 commented on front/package.json
> +    "lint": "next lint"
Seria bom adicionar um comando pra formatar os arquivos de acordo com que o lint acusar de errado. Também seria bom checar o com o _prettier_.

2023-05-01 16:37 UTC, gabsrp2002 commented on front/README.md
Acho que esse arquivo não é necessário.

2023-05-01 16:37 UTC, gabsrp2002 commented on front/src/pages/create.tsx
Parece que o esse arquivo não é utilizado em nenhum lugar na aplicação.

2023-05-05 15:09 UTC, gabsrp2002 requested changes

2023-05-05 15:09 UTC, gabsrp2002 commented on front/src/pages/create.tsx
> +      body: JSON.stringify({ text }),
O formato do JSON tá errado aqui, por isso que o botão não adiciona no banco de dados.

2023-05-26 20:22 UTC, brenofranca83 commented
Faltou mergear...?

2023-06-07 03:00 UTC, closed without merging